import type { NextPage } from "next";
import Head from "next/head";
import MainTemplate from "../templates/MainTemplate";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainTemplate />
    </div>
  );
};

export default Home;
